src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Article::class, orphanRemoval: true)]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setCategorie($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCategorie() === $this) {
                $article->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('submit', SubmitType::class, [
                'label' => 'Ajouter',
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Categorie;
use App\Entity\Article;
use App\Repository\CategorieRepository;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Form\CategorieType;
use Symfony\Component\Security\Http\Attribute\IsGranted;



class CategorieController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em, private CategorieRepository $categorieRepository, private ArticleRepository $articleRepository)
    {
    }

    #[Route('/', name: 'app_home')]
    public function home(): Response
    {
        $troisDerCategories = $this->categorieRepository->findBy([], ['id' => 'DESC'], 3);

        return $this->render('categorie/home.html.twig', [
            'categories' => $troisDerCategories,
            'articles' => $this->articleRepository->findAll(),
        ]);
    }
    #[Route('/categorie', name: 'app_categorie')]
    public function index(Request $request): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', 'La categorie n\'a pas été ajoutée.');
        } elseif ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($categorie);
            $this->em->flush();
            $this->addFlash('success', 'La categorie a bien été ajoutée.');
            return $this->redirectToRoute('app_categorie');
        }

        return $this->render('categorie/index.html.twig', [
            'controller_name' => 'CategorieController',
            'form' => $form->createView(),
            'categories' => $this->categorieRepository->findAll(),
            'articles' => $this->articleRepository->findAll(),
        ]);
    }
    #[Route('/categorie-details/{id}', name: 'detail_categorie')]
    public function details(Categorie $categorie = null)
    {
        if($categorie == null){
            return $this->redirectToRoute('app_categorie');
        }
        else{
            return $this->render('categorie/details.html.twig', [
                'categorie' => $categorie,
                'articles' => $this->articleRepository->findBy(['categorie' => $categorie->getId()]),
            ]);
        }
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/categorie-delete/{id}', name: 'delete_categorie')]
    public function delete($id)
    {
        $categorie = $this->em->getRepository(Categorie::class)->find($id); // Récupère la catégorie à modifier 

        if($categorie == null){
            return $this->redirectToRoute('app_categorie');
        }
        else{
            $articles = $categorie->getArticles();
            foreach($articles as $article){
                $commentaires = $article->getCommentaires();
                foreach($commentaires as $commentaire){
                    $this->em->remove($commentaire);
                }
                $this->em->remove($article);
            }
            $this->em->remove($categorie);
            $this->em->flush();
            $this->addFlash('success', 'La catégorie a bien été supprimée.');
            return $this->redirectToRoute('app_categorie');
        }
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/categorie-update/{id}', name: 'update_categorie')]
    public function editCategorie(Request $request, $id)
    {
        $categorie = $this->em->getRepository(Categorie::class)->find($id); // Récupère la catégorie à modifier
        $form = $this->createForm(CategorieType::class, $categorie); // Création du formulaire
        $form->handleRequest($request); // Gestion de la requête

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();
            $this->addFlash('success', 'Catégorie modifié avec succès');
            return $this->redirectToRoute('app_categorie');
        } 
        return $this->render('categorie/edit.html.twig', [
            'form' => $form->createView() // Envoi du formulaire à la vue
        ]);
    }
}

templates/categorie/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategorieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <div class="card">
        {{ categorie.titre }} 
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('update_categorie', {'id': categorie.id}) }}">Modifier</a> 
            <a href="{{ path('delete_categorie', {'id': categorie.id}) }}">Supprimer</a>
        {% endif %}
        {% if categorie.articles|length > 0 %}
            <p>Nombre d'articles : {{ categorie.articles|length }}</p>
            Article :
            {% for article in categorie.articles %}
                {% if article.etat == 1 %}
                    <a href="{{ path('detail_article', {'id': article.id}) }}">
                        {{ article.titre }}
                    </a>
            {% else %}
                <p>Article en cours d'écriture...</p>
            {% endif %}
        {% endfor %}
        {% else %}
            <p>Aucun article dans cette catégorie.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}modification catégorie{% endblock %}

{% block body %}
    <h1>Détails de la catégorie</h1>
    {% if is_granted('ROLE_ADMIN') %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    {% endif %}
{% endblock %}

templates/categorie/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategorieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {% if categories is not empty %}

        <h1>Les 3 Catégories les plus récentes !</h1>
        <ul>
            {% for categorie in categories %}
                <a href="{{ path('detail_categorie', {'id': categorie.id}) }}">
                <li>{{ categorie.titre }}</li>
                </a>
            {% endfor %}
        </ul>
    {% else %}
        <h1>Aucune catégorie n'a été trouvée.</h1>
    {% endif %}
</div>
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategorieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des catégories</h1>
    {% if is_granted('ROLE_ADMIN') %}
        {{ form(form) }}    
    {% endif %}

    {% for categorie in categories %}
        <div class="card">
            {{ categorie.titre }} 
            <a href="{{ path('detail_categorie', {'id': categorie.id}) }}">Voir</a>
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('update_categorie', {'id': categorie.id}) }}">Modifier</a> 
                <a href="{{ path('delete_categorie', {'id': categorie.id}) }}">Supprimer</a>
            {% endif %}

            {% if categorie.articles|length > 0 %}
                <p>Nombre d'articles : {{ categorie.articles|length }}</p>
            
            {% else %}
                <p>Aucun article dans cette catégorie.</p>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock %}